# Generated by Django 2.0.5 on 2019-07-11 21:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190711_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 21, 27, 5, 992516, tzinfo=utc)),
        ),
    ]
